[package]
name = "jas"
version = "0.1.0"
authors = ["Miguel Young <mcyoung@mit.edu>"]
edition = "2018"

[dependencies]
classfile = { path = "classfile" }
base64 = "0.9.0"
clap = "2.29.2"


[workspace]